time:
  secs: 1516239192
  nsecs: 554763553
link: 'left_hand'
joint: 'left_gripper_base'
urdf: '<?xml version="1.0" ?>
<robot name="left_end_effector">

  <link name="FT_bottom_plate_left">
    <inertial>
      <origin rpy="0 0 0" xyz="0.034783 -1.3323E-15 0.0055211"/>
      <mass value="0.1042"/>
      <inertia ixx="2.5588E-05" ixy="2.7505E-21" ixz="2.4673E-08" iyy="2.3459E-05" iyz="4.1597E-22" izz="4.7997E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT_bottom_plate.STL"/>
      </geometry>
      <material name="">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT_bottom_plate.STL"/>
      </geometry>
    </collision>
  </link>

  <link name="FT_left">
    <inertial>
      <origin rpy="0 0 0" xyz="0.003889 0.0057216 0.014109"/>
      <mass value="0.3772"/>
      <inertia ixx="0.0010241" ixy="0.00016944" ixz="2.4095E-05" iyy="0.00071846" iyz="5.2318E-05" izz="0.0014993"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT.STL"/>
      </geometry>
      <material name="">
        <color rgba="1 0.5 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT.STL"/>
      </geometry>
    </collision>
  </link>

  <link name="FT_Top_Plate_left">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.0067444 -3.2055E-10 0.0054943"/>
      <mass value="0.1"/>
      <inertia ixx="2.7087E-05" ixy="5.8629E-13" ixz="-2.2091E-08" iyy="2.5333E-05" iyz="4.732E-16" izz="5.1339E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT_Top_Plate.STL"/>
      </geometry>
      <material name="">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_baxter_description/urdf/ft/meshes/FT_Top_Plate.STL"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_gripper_base" type="fixed">
    <origin rpy="3.14159265359 3.14159265359 0" xyz="0.02 0 0"/>
    <parent link="left_hand"/>
    <child link="FT_bottom_plate_left"/>
  </joint>


  <joint name="l_FT_Bottom_Joint" type="fixed">
    <origin rpy="-3.1416 6.2028E-17 1.5708" xyz="0.041625 -0.00085087 0.040469"/>
    <parent link="FT_bottom_plate_left"/>
    <child link="FT_left"/>
    <axis xyz="0 0 0"/>
  </joint>

  <joint name="l_FT_Top_Joint" type="fixed">
    <origin rpy="3.1416 5.017E-16 1.5708" xyz="0.00085087 -0.00087515 -0.0030305"/>
    <parent link="FT_left"/>
    <child link="FT_Top_Plate_left"/>
    <axis xyz="0 0 1"/>
    <limit effort="0.2" lower="0" upper="0" velocity="0.2"/>
  </joint>
 
  <!-- Left End Effector -->
  <!-- Base of end effector -->
  <link name="left_gripper_base">
    <visual>
      <origin rpy="-1.57079632679 3.14159265359 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://birl_gripper_description/meshes/electric_gripper/electric_gripper_base.DAE"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="-1.57079632679 3.14159265359 0" xyz="0.0 0.0 0"/>
      <geometry>
        <cylinder length="0.1" radius="0.029"/>
      </geometry>
      <material name="darkred">
        <color rgba=".5 .1 .1 1"/>
      </material>
    </collision>
    <inertial>
      <origin rpy="-1.57079632679 3.14159265359 0" xyz="0.0 0.0 0.0"/>
      <mass value="0.3"/>
      <inertia ixx="2e-08" ixy="0" ixz="0" iyy="3e-08" iyz="0" izz="2e-08"/>
    </inertial>
  </link>

  <link name="l_gripper_l_finger">
    <visual>
      <origin rpy="0 0 -3.14159265359" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://rethink_ee_description/meshes/electric_gripper/fingers/standard_narrow.DAE"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 -3.14159265359" xyz="0 0.01725 0.04"/>
      <geometry>
        <box size="0.01 0.0135 0.075"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0 0 -3.14159265359" xyz="-0.005 -0.003 0.0083"/>
      <geometry>
        <box size="0.01 0.05 0.017"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 -3.14159265359" xyz="0 0 0"/>
      <mass value="0.02"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <link name="l_gripper_l_finger_tip">
    <visual>
      <origin rpy="0 0 3.14159265359" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://rethink_ee_description/meshes/electric_gripper/fingers/basic_hard_tip.DAE"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 3.14159265359" xyz="0 -0.0045 -0.015"/>
      <geometry>
        <box size="0.016 0.0065 0.037"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 3.14159265359" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="l_gripper_l_finger_tip_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.01725 0.075"/>
    <parent link="l_gripper_l_finger"/>
    <child link="l_gripper_l_finger_tip"/>
  </joint>

  <link name="l_gripper_r_finger">
    <visual>
      <origin rpy="0 0 -0.0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://rethink_ee_description/meshes/electric_gripper/fingers/standard_narrow.DAE"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 -0.0" xyz="0 -0.01725 0.04"/>
      <geometry>
        <box size="0.01 0.0135 0.075"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0 0 -0.0" xyz="0.005 0.003 0.0083"/>
      <geometry>
        <box size="0.01 0.05 0.017"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 -0.0" xyz="0 0 0"/>
      <mass value="0.02"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <link name="l_gripper_r_finger_tip">
    <visual>
      <origin rpy="0 0 0.0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://rethink_ee_description/meshes/electric_gripper/fingers/basic_hard_tip.DAE"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0.0" xyz="0 0.0045 -0.015"/>
      <geometry>
        <box size="0.016 0.0065 0.037"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0.0" xyz="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="l_gripper_r_finger_tip_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 -0.01725 0.075"/>
    <parent link="l_gripper_r_finger"/>
    <child link="l_gripper_r_finger_tip"/>
  </joint>

  <!-- Electric Gripper Base Joint -->
  <joint name="l_FT_left_gripper_base" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.025"/>
    <parent link="FT_Top_Plate_left"/>
    <child link="left_gripper_base"/>
  </joint>

  <!-- Electric Gripper Tip joint -->
  <joint name="left_endpoint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.095"/>
    <parent link="left_gripper_base"/>
    <child link="left_gripper"/>
  </joint>
  <!-- Electric Gripper Tip link -->
  <link name="left_gripper">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.0001"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
    </inertial>
  </link>
  <joint name="l_gripper_l_finger_joint" type="prismatic">
    <origin rpy="0 0 0" xyz="0.0 -0.0015 0.02"/>
    <axis xyz="0 1 0"/>
    <parent link="left_gripper_base"/>
    <child link="l_gripper_l_finger"/>
    <limit effort="20.0" lower="0.0" upper="0.020833" velocity="5.0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>
  <joint name="l_gripper_r_finger_joint" type="prismatic">
    <origin rpy="0 0 0" xyz="0.0 0.0015 0.02"/>
    <axis xyz="0 1 0"/>
    <parent link="left_gripper_base"/>
    <child link="l_gripper_r_finger"/>
    <limit effort="20.0" lower="-0.020833" upper="0.0" velocity="5.0"/>
    <mimic joint="l_gripper_l_finger_joint" multiplier="-1.0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>
</robot>'
